// <auto-generated />
using System;
using CookingProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookingProject.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookingProject.Api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Анна",
                            CreatedAt = new DateTime(2026, 2, 27, 13, 23, 10, 626, DateTimeKind.Utc).AddTicks(7167),
                            RecipeId = 10,
                            Text = "Очень вкусная шарлотка, дети в восторге!"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Игорь",
                            CreatedAt = new DateTime(2026, 2, 28, 13, 23, 10, 626, DateTimeKind.Utc).AddTicks(7174),
                            RecipeId = 1,
                            Text = "Шакшука получилась острой и сытной, рекомендую."
                        });
                });

            modelBuilder.Entity("CookingProject.Api.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CookingProject.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLactoseFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSugarFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuisine = "arabic",
                            Description = "Яйца в пряном томатном соусе с овощами.",
                            DishType = "main",
                            Image = "shakshuka.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = true,
                            IsVegetarian = true,
                            MainIngredient = "veggy",
                            Title = "Шакшука"
                        },
                        new
                        {
                            Id = 2,
                            Cuisine = "italian",
                            Description = "Классическая итальянская паста с мясным соусом.",
                            DishType = "main",
                            Image = "pasta.jpg",
                            IsGlutenFree = false,
                            IsLactoseFree = true,
                            IsSugarFree = false,
                            IsVegetarian = false,
                            MainIngredient = "meat",
                            Title = "Паста болоньезе"
                        },
                        new
                        {
                            Id = 3,
                            Cuisine = "american",
                            Description = "Салат с курицей, листовым салатом и соусом Цезарь.",
                            DishType = "salad",
                            Image = "salat.jpg",
                            IsGlutenFree = false,
                            IsLactoseFree = false,
                            IsSugarFree = false,
                            IsVegetarian = false,
                            MainIngredient = "meat",
                            Title = "Салат Цезарь"
                        },
                        new
                        {
                            Id = 4,
                            Cuisine = "french",
                            Description = "Классический луковый суп с гренками и сыром.",
                            DishType = "soup",
                            Image = "soup.jpg",
                            IsGlutenFree = false,
                            IsLactoseFree = false,
                            IsSugarFree = false,
                            IsVegetarian = true,
                            MainIngredient = "veggy",
                            Title = "Французский луковый суп"
                        },
                        new
                        {
                            Id = 5,
                            Cuisine = "japan",
                            Description = "Роллы с рисом и лососем, подаются с соевым соусом.",
                            DishType = "main",
                            Image = "rolls.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = true,
                            IsVegetarian = false,
                            MainIngredient = "fish",
                            Title = "Японские роллы с лососем"
                        },
                        new
                        {
                            Id = 6,
                            Cuisine = "china",
                            Description = "Лёгкий овощной суп с тофу.",
                            DishType = "soup",
                            Image = "china_soup.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = true,
                            IsVegetarian = true,
                            MainIngredient = "veggy",
                            Title = "Китайский овощной суп"
                        },
                        new
                        {
                            Id = 7,
                            Cuisine = "russian",
                            Description = "Традиционный русский гарнир из гречки с грибами.",
                            DishType = "garnish",
                            Image = "grechka.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = true,
                            IsVegetarian = true,
                            MainIngredient = "grain",
                            Title = "Гречка с грибами"
                        },
                        new
                        {
                            Id = 8,
                            Cuisine = "american",
                            Description = "Освежающий напиток на основе лимона и мяты без добавления сахара.",
                            DishType = "drink",
                            Image = "lemonade.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = true,
                            IsVegetarian = true,
                            MainIngredient = "veggy",
                            Title = "Домашний лимонад без сахара"
                        },
                        new
                        {
                            Id = 9,
                            Cuisine = "american",
                            Description = "Десерт на основе ягод и орехов без глютена и лактозы.",
                            DishType = "dessert",
                            Image = "berry_dessert.jpg",
                            IsGlutenFree = true,
                            IsLactoseFree = true,
                            IsSugarFree = false,
                            IsVegetarian = true,
                            MainIngredient = "veggy",
                            Title = "Вегетарианский ягодный десерт"
                        },
                        new
                        {
                            Id = 10,
                            Cuisine = "russian",
                            Description = "Классическая русская шарлотка с яблоками.",
                            DishType = "dessert",
                            Image = "sharlotka.jpg",
                            IsGlutenFree = false,
                            IsLactoseFree = false,
                            IsSugarFree = false,
                            IsVegetarian = true,
                            MainIngredient = "grain",
                            Title = "Шарлотка с яблоками"
                        });
                });

            modelBuilder.Entity("CookingProject.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BasePortions")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlexible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Яйца",
                            RecipeId = 1,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 2,
                            Amount = 400m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Помидоры",
                            RecipeId = 1,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лук",
                            RecipeId = 1,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Чеснок",
                            RecipeId = 1,
                            Unit = "зубчика"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Паприка",
                            RecipeId = 1,
                            Unit = "по вкусу"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 400m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Спагетти",
                            RecipeId = 2,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 500m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Фарш мясной",
                            RecipeId = 2,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Томатная паста",
                            RecipeId = 2,
                            Unit = "ст.л."
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лук",
                            RecipeId = 2,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 10,
                            Amount = 400m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Куриная грудка",
                            RecipeId = 3,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 200m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Листовой салат",
                            RecipeId = 3,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 50m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Пармезан",
                            RecipeId = 3,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Соус Цезарь",
                            RecipeId = 3,
                            Unit = "по вкусу"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 600m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лук репчатый",
                            RecipeId = 4,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Бульон",
                            RecipeId = 4,
                            Unit = "л"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 100m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Сыр грюйер",
                            RecipeId = 4,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 8m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Гренки",
                            RecipeId = 4,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 18,
                            Amount = 300m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Рис для суши",
                            RecipeId = 5,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 200m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лосось",
                            RecipeId = 5,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 4m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Нори",
                            RecipeId = 5,
                            Unit = "листа"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Васаби",
                            RecipeId = 5,
                            Unit = "по вкусу"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 200m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Тофу",
                            RecipeId = 6,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 200m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Брокколи",
                            RecipeId = 6,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Морковь",
                            RecipeId = 6,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 25,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Бульон овощной",
                            RecipeId = 6,
                            Unit = "л"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 200m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Гречка",
                            RecipeId = 7,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 300m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Шампиньоны",
                            RecipeId = 7,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лук",
                            RecipeId = 7,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 29,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Масло растительное",
                            RecipeId = 7,
                            Unit = "ст.л."
                        },
                        new
                        {
                            Id = 30,
                            Amount = 4m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Лимон",
                            RecipeId = 8,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 31,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Мята свежая",
                            RecipeId = 8,
                            Unit = "пучок"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Вода",
                            RecipeId = 8,
                            Unit = "л"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Стевия или мёд (по желанию)",
                            RecipeId = 8,
                            Unit = "по вкусу"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 300m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Ягоды свежие",
                            RecipeId = 9,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 100m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Орехи",
                            RecipeId = 9,
                            Unit = "г"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Кокосовая стружка",
                            RecipeId = 9,
                            Unit = "ст.л."
                        },
                        new
                        {
                            Id = 37,
                            Amount = 2m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Мёд",
                            RecipeId = 9,
                            Unit = "ст.л."
                        },
                        new
                        {
                            Id = 38,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Мука",
                            RecipeId = 10,
                            Unit = "стакан"
                        },
                        new
                        {
                            Id = 39,
                            Amount = 1m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Сахар",
                            RecipeId = 10,
                            Unit = "стакан"
                        },
                        new
                        {
                            Id = 40,
                            Amount = 3m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Яйца",
                            RecipeId = 10,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 41,
                            Amount = 4m,
                            BasePortions = 4,
                            IsFlexible = false,
                            Name = "Яблоки",
                            RecipeId = 10,
                            Unit = "шт."
                        },
                        new
                        {
                            Id = 42,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Ванилин",
                            RecipeId = 10,
                            Unit = "по вкусу"
                        },
                        new
                        {
                            Id = 43,
                            Amount = 0m,
                            BasePortions = 4,
                            IsFlexible = true,
                            Name = "Сода пищевая",
                            RecipeId = 10,
                            Unit = "щепотка"
                        });
                });

            modelBuilder.Entity("CookingProject.Api.Models.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 1,
                            StepOrder = 1,
                            Text = "Обжарить лук с чесноком на сковороде."
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 1,
                            StepOrder = 2,
                            Text = "Добавить помидоры, специи, тушить 10 минут."
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 1,
                            StepOrder = 3,
                            Text = "Сделать углубления, разбить яйца, накрыть и готовить до готовности белка."
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = 2,
                            StepOrder = 1,
                            Text = "Обжарить фарш с луком, добавить томатную пасту и тушить 20 мин."
                        },
                        new
                        {
                            Id = 5,
                            RecipeId = 2,
                            StepOrder = 2,
                            Text = "Отварить спагетти согласно инструкции на упаковке."
                        },
                        new
                        {
                            Id = 6,
                            RecipeId = 2,
                            StepOrder = 3,
                            Text = "Подавать пасту с соусом болоньезе."
                        },
                        new
                        {
                            Id = 7,
                            RecipeId = 3,
                            StepOrder = 1,
                            Text = "Обжарить куриную грудку, нарезать полосками."
                        },
                        new
                        {
                            Id = 8,
                            RecipeId = 3,
                            StepOrder = 2,
                            Text = "Смешать салат, курицу, пармезан, заправить соусом Цезарь."
                        },
                        new
                        {
                            Id = 9,
                            RecipeId = 4,
                            StepOrder = 1,
                            Text = "Пассеровать лук до карамелизации."
                        },
                        new
                        {
                            Id = 10,
                            RecipeId = 4,
                            StepOrder = 2,
                            Text = "Залить бульоном, варить 20 минут. Подавать с гренками и сыром."
                        },
                        new
                        {
                            Id = 11,
                            RecipeId = 5,
                            StepOrder = 1,
                            Text = "Отварить рис для суши, остудить."
                        },
                        new
                        {
                            Id = 12,
                            RecipeId = 5,
                            StepOrder = 2,
                            Text = "Раскладывать рис на нори, добавлять лосось, заворачивать роллы."
                        },
                        new
                        {
                            Id = 13,
                            RecipeId = 5,
                            StepOrder = 3,
                            Text = "Нарезать роллы, подавать с соевым соусом и васаби."
                        },
                        new
                        {
                            Id = 14,
                            RecipeId = 6,
                            StepOrder = 1,
                            Text = "Довести бульон до кипения, добавить нарезанные овощи и тофу."
                        },
                        new
                        {
                            Id = 15,
                            RecipeId = 6,
                            StepOrder = 2,
                            Text = "Варить 10–15 минут, подавать горячим."
                        },
                        new
                        {
                            Id = 16,
                            RecipeId = 7,
                            StepOrder = 1,
                            Text = "Отварить гречку."
                        },
                        new
                        {
                            Id = 17,
                            RecipeId = 7,
                            StepOrder = 2,
                            Text = "Обжарить грибы с луком, смешать с гречкой."
                        },
                        new
                        {
                            Id = 18,
                            RecipeId = 8,
                            StepOrder = 1,
                            Text = "Выжать сок лимонов, добавить воду и мяту."
                        },
                        new
                        {
                            Id = 19,
                            RecipeId = 8,
                            StepOrder = 2,
                            Text = "Охладить, подавать со льдом."
                        },
                        new
                        {
                            Id = 20,
                            RecipeId = 9,
                            StepOrder = 1,
                            Text = "Смешать ягоды, орехи, кокосовую стружку и мёд."
                        },
                        new
                        {
                            Id = 21,
                            RecipeId = 9,
                            StepOrder = 2,
                            Text = "Разложить по креманкам, подавать охлаждённым."
                        },
                        new
                        {
                            Id = 22,
                            RecipeId = 10,
                            StepOrder = 1,
                            Text = "Взбить яйца с сахаром, добавить муку с содой и ванильным сахаром."
                        },
                        new
                        {
                            Id = 23,
                            RecipeId = 10,
                            StepOrder = 2,
                            Text = "Яблоки нарезать дольками, смешать с тестом."
                        },
                        new
                        {
                            Id = 24,
                            RecipeId = 10,
                            StepOrder = 3,
                            Text = "Выложить в форму, выпекать при 190°C 30 минут."
                        });
                });

            modelBuilder.Entity("CookingProject.Api.Models.Comment", b =>
                {
                    b.HasOne("CookingProject.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookingProject.Api.Models.Favorite", b =>
                {
                    b.HasOne("CookingProject.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookingProject.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookingProject.Api.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookingProject.Api.Models.RecipeStep", b =>
                {
                    b.HasOne("CookingProject.Api.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookingProject.Api.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
